### PR TITLE
Allowing optional disabling of registry polling.

### LINKED ISSUE #30: Add option to disable polling for instance info
If your application only needs to register with eureka and doesn't need information on other instances, there is no option to disable polling to /eureka/v2/apps.

I propose allowing eureka.registryFetchInterval set to a value to allow disabling of polling.  

Would you accept a pull request?

What should getInstancesByAppId and getInstancesByVipAddress return?  Empty arrays?
What value should eureka.registryFetchInterval be set to disable polling?  The null value works with deepmerge, but would be a breaking change, how about "DO_NOT_FETCH"?

### PR DESCRIPTION
**Pull request by kesne**
Resolves #30.

### CODE REVIEW

**Comment by kesne** [comment]
This will probably drop on coverage because I didn't write tests. I can get around to that later tonight.

**Comment by daveedgarcia** [comment]
-_- on the tests but looks good to me.

**Comment by kesne** [comment]
Don't worry I'll do the tests later today before I merge it in.

**Comment by jquatier** [comment]
I'll write them. :)

**Pull request merged**
