### PR TITLE
Move to Airbnb Style Guide (+ increase @kesne git fame)

### PR DESCRIPTION
**Pull request by kesne**
This does more than the title suggests because I'm a liar.

- Upgrade to babel 6.
- Start linting our tests (there were a lot of lint errors here).
- Start running tests on stable node.
- Convert to Airbnb Styleguide.
- #simplify

### CODE REVIEW

**Comment by kesne** [comment]
Well, that took way too long to figure out, but build is finally green. :+1:

**Comment by eltonjuan** [comment]
Nice job :+1:

**Comment by kesne** [comment]
@jquatier have you had a chance to test this?

**Comment by jquatier** [comment]
workin on it, should be in by tomorrow.

**Comment by jquatier** [comment]
Great PR. Thanks dude!

**Comment by kesne** [comment]
You're welcome homie.

**Pull request merged**
