### PR TITLE
[config] Adding configurable instanceid.

### LINKED ISSUE #42: Option for setting instanceId.
We have the need to run multiple instances of the same service on the same host machine.
This is not possible then the InstanceId field is automatically defined using the hostname.

I would like the option to set the instanceId field in the configuration array for the Eureka client.

### PR DESCRIPTION
**Pull request by kesne**
We had a request to configure the instance id based on configuration. Fixes #42.

### CODE REVIEW

**Comment by daveedgarcia** [comment]
Looks good. We can have JQ merge it after he takes a look.

**Comment by kesne** [comment]
I can also yolo merge it.

**Comment by jquatier** [comment]
Thx! I'll do a minor release tonight.

**Comment by kesne** [comment]
Ur wlcme

**Comment by mogensen** [comment]
There seems to be a small technicality here still. If we don't supply an instanceId in the initial registration to Eureka, eureka will choose the hostname as the instanceid. 
This means that when we try to renew the lease afterwards, using the configured instanceId from the instance object, we get a 404 back. This is returned because the instanceId we use in the url to eureka is not registered in eureka.

So we need to add the instanceId to the initial registration json object. Or rename the new property from 
 `this.config.instance.id` to `this.config.instance.instanceId`.

**Comment by jquatier** [comment]
I don't see `instanceId` in their XSD. In fact they explicitly say in their documentation that in non-Amazon data centers the instance ID is the hostname. So, if that's true the the Eureka server is still using the hostname (because this is a non-AWS machine), there might not be much we can do. But, I'll try it today and see if `instanceId` in the registration POST body has any effect.

**Comment by mogensen** [comment]
Hmm. Yes I see that they don't mention it. I am using the Spring-Cloud wrapper for the Netflix Eureka Server. At least with this instance of the Eureka server i can set the instance id by: 

    var client = new Eureka({
        instance: {
            id: myInstanceId,
            instanceId: myInstanceId,
    ...

This makes sure that eureka registers the service with `myInstanceId` and with the code from this pull request I can renew the lease as well.

**Comment by jquatier** [comment]
Alright, looks like that does work. It seems it's just an undocumented property... https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java

Anyway, we can do a release to update the property name so that you don't have to specify it twice. I think that's better anyway so it matches the undocumented property. Technically it's a breaking change since the old property wont work anymore, but I'd rather not do a Major version tick.

**Comment by jquatier** [comment]
Alright, the new property name is `instanceId` and it's in v2.3.1. For what it's worth, I still get 404s when it tried to renew the lease because it can't find that instanceID. If I use their documented GET operation to get an instance by ID it also returns a 404.

GET /eureka/v2/instances/<instanceId> -- 404

There might be an override in the Spring Cloud version of the server that allows this to work. In any case, at least you wont have to define it twice.

**Comment by mogensen** [comment]
Perfect! This fulfills all my needs for now. Thanks a lot to you all!
:thumbsup:

**Pull request merged**
